### ISSUE TITLE
Create a better time table

### ISSUE THREAD

**Issue by dvberkel** [Balletboetiek/website#2]
The timetable currently is copied verbatim from the original website. As such it has a lot of manual styling.

Lets clean it up

**Comment by Balletboetiek** [comment]
top, kunnen we ook de kleuren aanpassen :-)

**Comment by dvberkel** [comment]
Als je de issue sluit dan vergeten wij misschien dat wij er nog iets mee moeten doen :-)

**Comment by dvberkel** [comment]
Voorstel voor een time table.

Zou het wat zijn dat jij dingen schrijft als hieronder staat?

```
| Tijd | Maandag | Dinsdag | Woensdag | Donderdag | Vrijdag |
|12:00-13:00| **K2** kinderballet 4-6 jaar | | | | |
```

En dat daar dan een mooie tabel uit komt?

**Comment by dvberkel** [comment]
Fixed in commit a136b79db99eb7eabfd56d69266a46abcaddf59c
