### ISSUE TITLE
Discuss photo caroussel

### ISSUE THREAD

**Issue by dvberkel** [Balletboetiek/website#3]
Now the foto's are not shown, or I am mistaken.

It would be a great thing to show them

**Comment by Balletboetiek** [comment]
you can propose a solution

**Comment by dvberkel** [comment]
[PhotoSwipe](http://photoswipe.com/) seems a good library that offers a comprehensive gallery

**Comment by dvberkel** [comment]
I settled on the [galleria](https://galleria.io) framework incorporating it now
